# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bsm-breadcrumbs}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira", "Dimitrij Denissenko"]
  s.date = %q{2011-02-16}
  s.description = %q{Breadcrumbs is a simple plugin that adds a `breadcrumbs` object to controllers and views.}
  s.email = %q{dimitrij@blacksquaremedia.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "bsm-breadcrumbs.gemspec",
    "lib/breadcrumbs.rb",
    "lib/breadcrumbs/action_controller_ext.rb",
    "lib/breadcrumbs/render.rb",
    "lib/breadcrumbs/render/base.rb",
    "lib/breadcrumbs/render/inline.rb",
    "lib/breadcrumbs/render/list.rb",
    "lib/breadcrumbs/render/ordered_list.rb",
    "lib/breadcrumbs/version.rb",
    "test/breadcrumbs_test.rb",
    "test/resources/en.yml",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/bsm/breadcrumbs}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Breadcrumbs is a simple plugin that adds a `breadcrumbs` object to controllers and views.}
  s.test_files = [
    "test/breadcrumbs_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_dependency(%q<activemodel>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
    s.add_dependency(%q<activemodel>, ["~> 3.0.0"])
  end
end

